services:
  # Frontend development server with hot reload
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    environment:
      - VITE_API_URL=http://localhost:8080
    networks:
      - rememo-dev
    restart: unless-stopped

  # Backend development server with hot reload
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      # Database Configuration
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_NAME=rememo
      - DB_USER=rememo_user
      - DB_PASSWORD=rememo_password
      
      # LLM Configuration - External provider
      - LLM_PROVIDER=${LLM_PROVIDER:-openai}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - OPENAI_BASE_URL=${OPENAI_BASE_URL:-https://api.openai.com/v1}
      
      # AI Model Configuration
      - DEFAULT_MODEL=${DEFAULT_MODEL:-gpt-4o-mini}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-text-embedding-3-small}
      - SYSTEM_PROMPT=${SYSTEM_PROMPT:-You are a helpful AI assistant for journaling and self-reflection.}
      - EMBEDDING_DIMENSION=${EMBEDDING_DIMENSION:-1536}

      # App Configuration
      - APP_HOST=0.0.0.0
      - APP_PORT=8080
      - DEBUG=true
      - SECRET_KEY=${SECRET_KEY:-dev-secret-key-change-this}
      
      # Feature Flags
      - ENABLE_VOICE=${ENABLE_VOICE:-true}
      - MAX_ENTRY_LENGTH=${MAX_ENTRY_LENGTH:-10000}
      - MAX_FACTS_PER_ENTRY=${MAX_FACTS_PER_ENTRY:-20}
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./backend/app:/app/app
      - ./backend/migrate.py:/app/migrate.py
      - ./logs:/app/logs
    networks:
      - rememo-dev
    restart: unless-stopped

  # PostgreSQL database
  postgres:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"  # Expose for external access if needed
    environment:
      POSTGRES_DB: rememo
      POSTGRES_USER: rememo_user
      POSTGRES_PASSWORD: rememo_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - rememo-dev
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rememo_user -d rememo"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_dev_data:
    driver: local

networks:
  rememo-dev:
    driver: bridge

# Usage:
# 1. Set your OpenAI API key: export OPENAI_API_KEY=your_key_here
# 2. Start development environment: docker-compose -f docker-compose.dev.yml up
# 3. Frontend will be available at: http://localhost:5173
# 4. Backend API will be available at: http://localhost:8080
# 5. PostgreSQL will be available at: localhost:5432
